name: 'Docker Build'
description: 'Reusable Docker Build steps'
inputs:
  aws-account:
    description: 'AWS Account ID'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: us-east-1
  aws-ecr-repo:
    description: 'AWS ECR Repository'
    required: true
  build-args:
    description: 'Docker Build Arguments'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Build production image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        # Set the desired build target here
        push: true
        build-args: ${{ inputs.build-args }}
        tags: |
          ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.aws-ecr-repo }}:${{ github.ref_name }}-latest
          ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.aws-ecr-repo }}:${{ github.sha }}
          ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.aws-ecr-repo }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
